In [1]:
#q1
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a=a.tolist()
print(a)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [4]:
#q2
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b= np.trace(a)
print(b)


12


In [6]:
#q3
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print("values are greater than x are : " , a[a>5])

values are greater than x are :  [6 7 8]


In [8]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b=np.array([[0,1,2],[3,4,5],[6,7,8]])
c=a+b
print(c)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [11]:
#q5
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b= np.mean(a)
c=a-b
print(c)

[[-4. -3. -2.]
 [-1.  0.  1.]
 [ 2.  3.  4.]]
